---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: local-example
  name: local-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-example
  template:
    metadata:
      labels:
        app: local-example
    spec:
      containers:
      - image: local/example
        name: example
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
  name: example
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example
  type: ClusterIP
